### ISSUE TITLE
Sporadic, exit memory error using MallocCheckHeapEach flag

### ISSUE THREAD

**Issue by cheesema** [cheesema/LibAPR#31]
There is still a bug, with MallocCheckHeapEach, from an Hdf5 garbage collector, that sporadically causes an error on exit with the flag enabled. Can't figure out whats causing it. 

Get it every 2-3 run Example_apr_iterate on master, running on osx.

Valgrind has no issues, excluding the pointers in the register_blosc(), function.

**Comment by cheesema** [comment]
Let me check if this is also still an issue.

**Comment by cheesema** [comment]
Yip, I get it running still every 2-3 runs on Example_apr_iterate, using sphere_apr.h5 (120)

When using the following flag: MallocCheckHeapStart

**Comment by krzysg** [comment]
I do not think that problem is connected to APR directly. I can reproduce it with such a simple example:
``` C++
extern "C" {
	#include "hdf5.h"
}

int main() {
hid_t fid = H5Fopen("x.h5", H5F_ACC_RDONLY,H5P_DEFAULT);
hid_t obj_id = H5Gopen2(fid,"ParticleRepr/t",H5P_DEFAULT);
hid_t data_id = H5Dopen2(obj_id, "particle_intensities", H5P_DEFAULT);
H5Dclose(data_id);
H5Gclose(obj_id);
H5Fclose(fid);
}
```
so it happens even without reading data at all and seems to come from HDF5 library.

It might be also that sth is wrong with MallocCheckHeapStart itself. It happens that it kills my vim editor for example and it happens only when this check is activated.
```Vim: Caught deadly signal SEGV```

**Comment by cheesema** [comment]
I thought something strange could be the case, very interesting!, guess we can close this. Good work :)
