### ISSUE TITLE
Example build error in Ubuntu 14.04

### ISSUE THREAD

**Issue by RenieWell** [cheesema/LibAPR#83]
I could successfully install LibAPR, but when I try to build the example file I met some problem.
My system is Ubuntu 14.04
CMake version: 3.6.3
GCC version: 5.2.0 
When I try to run the "cmake-build.sh "script in the LibAPR folder, I got the following error:
![screenshot from 2018-04-20 10_50_01](https://user-images.githubusercontent.com/4987555/39028653-4d34cd7a-448a-11e8-9e08-91cea60f6057.png)
So I try to install the snappy lib in https://github.com/google/snappy
However, it couldn't fix my problem.
I also try to build example in the examples/build folder, still didn't find a way out. I got the following error.
![screenshot from 2018-04-20 10_49_34](https://user-images.githubusercontent.com/4987555/39028729-c882d08a-448a-11e8-89a6-fb0a81fe081f.png)
It seems a Cpp standard error, so I changed the CMakeLists.txt file in the examples folder by adding "set (CMAKE_CXX_STANDARD 14)".  But it still get the error as following:
![screenshot from 2018-04-20 11_08_54](https://user-images.githubusercontent.com/4987555/39028955-012c106c-448c-11e8-9573-bf3650a5f8a3.png)

I am not very familiar with Cpp, can you gave me some advice?
I would be very grateful for your help！

**Comment by cheesema** [comment]
Thanks for posting, we will look into it and get back to you soon :)

**Comment by krzysg** [comment]
Hi, thank you for reporting that problem.
I can see that problem is with snappy library and also that c-blosc is trying to use external one instead provided with c-blosc. Could you please try to modify main CMakeLists.txt file, by adding line:

```
set(PREFER_EXTERNAL_SNAPPY OFF CACHE BOOL "" FORCE)
```

in the place where blosc is configured so, just after those lines (but before add_subdirectory("external/c-blosc/blosc")):
```
set(BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(BUILD_BENCHMARKS OFF CACHE BOOL "" FORCE)
set(BUILD_SHARED OFF CACHE BOOL "" FORCE)
set(BUILD_STATIC ON CACHE BOOL "" FORCE)

```

It seems that it is corrected on latest c-blosc and PREFER_EXTERNAL_SNAPPY is now by default OFF.

**Comment by RenieWell** [comment]
It works!
Thank you!

**Comment by krzysg** [comment]
Great! I will add that line to our CMakeLists.txt.
